<?php $this->headTitle("Login") ?>

<div class="row">
    <h2>Login</h2>

    <div class="col-md-6 col-md-offset-3">
        <?php if ($this->error) : ?>
            <div class="alert alert-danger">
                <p>Credenziali di accesso non valide.</p>
            </div>
        <?php endif; ?>

        <form action="<?php echo $this->url("login/post"); ?>" class="form-horizontal" id="loginForm" method="post" role="form">
            <div class="form-group">
                <label class="col-sm-2 control-label" for="username">Username</label>
                <div class="col-sm-10">
                    <input class="form-control" id="username" name="username" placeholder="Username" required="required" type="text">
                </div>
            </div>

            <div class="form-group">
                <label class="col-sm-2 control-label" for="password">Password</label>
                <div class="col-sm-10">
                    <input class="form-control" id="password" name="password" placeholder="Password" required="required" type="password">
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button class="btn btn-success" type="submit">Accedi</button>
                </div>
            </div>
        </form>
    </div>
</div>